/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SQT.View;

import SQT.Controller.Core.AbsMode;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author 21AK22
 */
public class RunFrame extends javax.swing.JFrame {

    /**
     * Creates new form RunFrame
     */
    private Thread thread;
    private boolean run;
    private int index = 1;
    private int success = 0;
    private int time = 0;
    private final Timer timer;
    private final AbsMode mode;
    public RunFrame(AbsMode mode) {
        initComponents();
        this.mode = mode;
        this.timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                lbTime.setText((time++) +" s");
            }
        });
    }
    
    public boolean isRun() {
        return thread != null && thread.isAlive();
    }
    
    private void showFrame() {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(copyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        super.setVisible(true);
        this.timer.start();
    }
    
    public void success() {
        success++;
    }
    
    public void nextIndex() {
        index ++;
    }
    
    public void stop() {
        this.run = false;
        this.success = 0;
        this.index = 0;
        this.time = 0;
        this.timer.stop();
        this.setVisible(false);
    }
    
    public void run(int max) {
        if (max < 1) {
            return;
        }
        this.process.setMaximum(max);
        this.process.setMinimum(0);
        this.process.setValue(0);
        this.process.setStringPainted(true);
        this.run = true;
        showFrame();
        this.thread = new Thread() {
            @Override
            public void run() {
                while (run) {
                    lbMun.setText(String.format("%s / %s", success, process.getMaximum()));
                    process.setValue(index);
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        break;
                    }
                }
            }
        };
        this.thread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        process = new javax.swing.JProgressBar();
        lbMun = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();

        setTitle(" Run");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(102, 102, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lbMun.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbMun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMun.setText("......");

        lbTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTime.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(process, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addComponent(lbMun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbMun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(process, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTime))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.mode.stopScan();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbMun;
    private javax.swing.JLabel lbTime;
    private javax.swing.JProgressBar process;
    // End of variables declaration//GEN-END:variables

    
}
